version: '3.8'

services:
  game-pantheon:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-pantheon:latest
    container_name: game-pantheon
    restart: unless-stopped
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - nginx-cache:/var/cache/nginx
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local 